part of views;

final infoArgsLookup = {
  '-cfg': 'Open configuration window',
  '-ea': 'Enable integrated EA server',
  '-eamaint': 'Enable integrated EA server',
  '-w': 'Windowed mode',
  '-c': 'Capture/clip mouse to window',
  '-s': 'Unhide cursor',
  '-k': 'Inject custom hook',
  '-stubs': 'Enable loading stubs',
  '-io': 'Manually enable ALL IO emulation',
  '-acio': 'Manually enable ACIO emulation',
  '-icca': 'Manually enable ICCA emulation',
  '-device': 'Manually enable DEVICE emulation',
  '-extdev': 'Manually enable EXTDEV emulation',
  '-sciunit': 'Manually enable SCIUNIT emu',
  '-sdvx': 'Manually enable SDVX module',
  '-iidx': 'Manually enable IIDX module',
  '-iidxflipcams': 'Flip the camera order',
  '-jb': 'Manually enable JB module',
  '-rb': 'Manually enable Reflec Beat module',
  '-pnm': 'Manually enable Pop\'n Music module',
  '-mga': 'Manually enable Metal Gear module',
  '-gd': 'Manually enable GitaDora module',
  '-nostalgia': 'Manually enable Nostalgia module',
  '-bbc': 'Manually enable BishiBashi Channel module',
  '-2ch': 'Two channel audio for GitaDora',
  '-ddr': 'Manually enable DDR module',
  '-ddrsd': 'Enable DDR 4:3 mode',
  '-o': 'Enable DDR 4:3 mode',
  '-qma': 'Enable QMA module',
  '-sc': 'Enable SC module',
  '-network': 'Netfix network',
  '-subnet': 'Netfix subnet',
  '-netfixdisable': 'Disable network patches',
  '-acphookdisable': 'Disable ACP patches',
  '-signaldisable': 'Disable signal handling',
  '-createfiledebug': 'CreateFile debug prints',
  '-pebprint': 'Print PEB on startup',
  '-bt5api': 'Partial BT5 API compat layer',
  '-printer': 'SDVX Printer Emulation',
  '-printerpath': 'SDVX Printer Output Directory',
  '-printerformat': 'SDVX Printer Format (png/bmp/tga/jpg)',
  '-printerjpgquality': 'SDVX Printer JPG quality',
  '-printerclear': 'Clean up images on start',
  '-urlslash': 'Set urlslash value',
  '-disablenumpad': 'Disable numpad for reader',
  '-disabletoprow': 'Disable toprow for reader',
  '-realtime': 'Base process priority is RT',
  '-sleep': 'Delay (5s before boot)',
  '-h': 'Custom heap size in bytes',
  '-a': 'Custom path to app-config.xml',
  '-v': 'Custom path to avs-config.xml',
  '-e': 'Custom path to ea3-config.xml',
  '-y': 'Custom path to log.txt',
  '-p': 'Custom PCBID override',
  '-r': 'Custom SOFTID override',
  '-url': 'Custom service URL',
  '-modules': 'Set path to modules',
  '-scard': 'Use HID SmartCard readers',
  '-scardflip': 'Smartcard P1/P2 order flip',
  '-scardtoggle': 'Smartcard P1/P2 NumLock toggle',
  '-reader': 'COM ICCA card reader',
  '-togglereader': 'With NumLock toggle',
  '-cardio': 'Enable HID card readers',
  '-cardioflip': 'Cardio P1/P2 order flip',
  '-sde': 'Intel SDE automatic attach',
  '-api': 'Enable API',
  '-apipass': 'Set API password',
  '-apipretty': 'Pretty JSON printing',
  '-apilogging': 'Enable API logs (dec. perf.)',
  '-apidebug': 'Run API only on debug settings',
  '-dbghookdisable': 'Disable debug message logging',
};

final info2PartArgsLookup = [
  '-k', '-network', '-subnet', '-printerpath', '-printerformat',
  '-printerjpgquality', '-urlslash', '-h', '-a', '-v', '-e', '-y', '-p', '-r',
  '-url', '-modules', '-reader', '-togglereader', '-sde', '-api', '-apipass',
  '-eamaint',
];

final playerCountMap = {
  "000": 2, // for debugging purposes
  "KFC": 1,
  "LDJ": 2,
  "J44": 1,
  "K44": 1,
  "L44": 1,
  "KDM": 1,
  "NBT": 1,
  "I36": 1,
  "MBR": 1,
  "M39": 1,
  "KGG": 1,
  "JGT": 1,
  "PIX": 1,
  "R66": 1, // actually has 4 players but only one reader
  "M32": 2, // guitars have 2 readers, drums only one
  "KDX": 2,
  "MDX": 2,
  "PAN": 1,
  "LMA": 1,
  "MMD": 1,
};

int getPlayerCount(String model) {
  return playerCountMap[model] ?? 2;
}
