name: flutter_nfc_reader
description: A nfc reader plugin for iOS and Android. This plugin allow you to trigger NFC native reading session on device.
version: 0.0.23
author: Matteo Crippa <matteocrippa>
homepage: https://github.com/matteocrippa/flutter-nfc-reader

environment:
  sdk: '>=1.19.0 <3.0.0'
  flutter: '>= 0.9.3-pre'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: it.matteocrippa.flutternfcreader
    pluginClass: FlutterNfcReaderPlugin
